"use client"
import { Inter } from "next/font/google";
import "./globals.css";

import { AuthType } from '@particle-network/auth-core';
import { SolanaTestnet } from '@particle-network/chains';
import { AuthCoreContextProvider, PromptSettingType } from '@particle-network/auth-core-modal';


const inter = Inter({ subsets: ["latin"] });
/*
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AuthCoreContextProvider
      options={{
        projectId: process.env.NEXT_PUBLIC_PROJECT_ID,
        clientKey: process.env.NEXT_PUBLIC_CLIENT_KEY,
        appId: process.env.NEXT_PUBLIC_APP_ID,
        authTypes: [AuthType.email, AuthType.google, AuthType.twitter, AuthType.metamask],
        themeType: 'dark',
        fiatCoin: 'USD',
        language: 'en',
        erc4337: {
          name: 'SIMPLE',
          version: '1.0.0',
        },
        promptSettingConfig: {
          promptPaymentPasswordSettingWhenSign: PromptSettingType.first,
          promptMasterPasswordSettingWhenLogin: PromptSettingType.first,
        },
        wallet: {
          visible: true,
          customStyle: {
            supportChains: [SolanaTestnet],
          }
        },
      }}
    >
      {children}
      </AuthCoreContextProvider>
      </body>
    </html>
  );
}
